"""
Generates Figures 1-4 for the Lancet Planetary Health manuscript from
the aggregated CCLW dataset (aggregated_data_file__2_.xlsx).

Note: Figure 5 (the institutional health-role choropleth map) is NOT
generated by this script -- it is reused directly from the original
appendix (extracted from the .docx media folder), since recreating a
world-map choropleth would require geopandas + shapefiles, which are
not part of this pipeline. If you want a script-generated map instead,
let me know and I'll add a geopandas/plotly version.

Usage:
    python make_figures.py

Edit DATA_PATH and OUT below if your file/output locations differ.
"""

import os
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ---------------------------------------------------------------
# Configuration -- edit these two paths for your environment
# ---------------------------------------------------------------
DATA_PATH = "./outputs/dataframes/aggregated_data_file.xlsx"   # path to the aggregated dataset
OUT = "./outputs/figures"                                # output directory for generated figures
os.makedirs(OUT, exist_ok=True)

plt.rcParams.update({
    "font.family": "sans-serif",
    "font.sans-serif": ["DejaVu Sans", "Arial", "Helvetica"],
    "font.size": 10,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.edgecolor": "#333333",
    "axes.labelcolor": "#222222",
    "text.color": "#222222",
    "xtick.color": "#333333",
    "ytick.color": "#333333",
    "axes.titlesize": 11,
    "axes.titleweight": "bold",
    "figure.facecolor": "white",
    "savefig.facecolor": "white",
})

# Okabe-Ito colourblind-safe palette
C_BLUE   = "#0072B2"
C_ORANGE = "#E69F00"
C_GREEN  = "#009E73"
C_VERMIL = "#D55E00"
C_GRAY   = "#888888"
C_DARK   = "#1B2A38"
C_TEAL   = "#0E5C63"

xls = pd.ExcelFile(DATA_PATH)
glob = pd.read_excel(xls, "Global")
hdi  = pd.read_excel(xls, "HDI")
lc   = pd.read_excel(xls, "LC")
who  = pd.read_excel(xls, "WHO")

# ---------------------------------------------------------------
# Figure 1: Global active legislative stock trends, 2000-2025
# Panel A: total / health-relevant / institutional active stock
# Panel B: institutional integration rate (% of health-relevant)
# ---------------------------------------------------------------
fig, axes = plt.subplots(1, 2, figsize=(9.5, 4.2))

ax = axes[0]
ax.plot(glob["Year"], glob["Total documents"], color=C_GRAY, lw=2, label="All climate legislation")
ax.plot(glob["Year"], glob["Health-relevant documents"], color=C_BLUE, lw=2.2, label="Health-relevant legislation")
ax.plot(glob["Year"], glob["Institutional health roles"], color=C_VERMIL, lw=2.2, label="Institutional health-role legislation")
ax.axvline(2016, color="black", lw=1, ls="--", alpha=0.6)
ax.text(2016.3, ax.get_ylim()[1]*0.92, "Paris Agreement\nenters into force", fontsize=8, color="#444444")
ax.set_xlabel("Year")
ax.set_ylabel("Active legislative stock (no. of policy families)")
ax.set_title("A   Global active legislative stock", loc="left")
ax.set_xlim(2000, 2025)

# Secondary (right-hand) axis: health-relevant share of all active legislation, per year
ax2 = ax.twinx()
pct_health = 100 * glob["Health-relevant documents"] / glob["Total documents"]
ax2.plot(glob["Year"], pct_health, color=C_GREEN, lw=1.8, ls="--", label="Health-relevant share of all legislation (right axis)")
ax2.set_ylabel("Health-relevant share of\nall active legislation (%)", color=C_GREEN)
ax2.tick_params(axis="y", colors=C_GREEN)
ax2.set_ylim(0, 100)
ax2.spines["right"].set_visible(True)
ax2.spines["right"].set_color(C_GREEN)

# Combined legend from both axes
h1, l1 = ax.get_legend_handles_labels()
h2, l2 = ax2.get_legend_handles_labels()
ax.legend(h1 + h2, l1 + l2, frameon=False, fontsize=7.5, loc="upper left")

ax = axes[1]
rate = 100 * glob["Institutional health roles"] / glob["Health-relevant documents"]
ax.plot(glob["Year"], rate, color=C_TEAL, lw=2.2)
ax.fill_between(glob["Year"], rate, color=C_TEAL, alpha=0.12)
ax.axvline(2016, color="black", lw=1, ls="--", alpha=0.6)
ax.set_xlabel("Year")
ax.set_ylabel("Institutional integration rate\n(% of health-relevant documents)")
ax.set_title("B   Global institutional integration rate", loc="left")
ax.set_xlim(2000, 2025)
ax.set_ylim(0, max(rate)*1.25)

fig.tight_layout()
fig.savefig(f"{OUT}/fig1_global_trends.pdf", bbox_inches="tight")
fig.savefig(f"{OUT}/fig1_global_trends.png", dpi=300, bbox_inches="tight")
plt.close(fig)

# ---------------------------------------------------------------
# Figure 2: Active stock by climate-response type, 2000-2025
# ---------------------------------------------------------------
fig, ax = plt.subplots(figsize=(7.2, 4.2))
cats = ["Mitigation", "Adaptation", "Disaster Risk Management", "Loss And Damage"]
cols = [C_BLUE, C_ORANGE, C_GREEN, C_VERMIL]
labels = ["Mitigation", "Adaptation", "Disaster risk management", "Loss and damage"]
for cat, col, lab in zip(cats, cols, labels):
    ax.plot(glob["Year"], glob[cat], color=col, lw=2.1, label=lab)
ax.axvline(2016, color="black", lw=1, ls="--", alpha=0.6)
ax.text(2016.3, ax.get_ylim()[1]*0.9, "Paris Agreement", fontsize=8, color="#444444")
ax.set_xlabel("Year")
ax.set_ylabel("Active legislative stock (no. of policy families)")
ax.set_title("Active legislative stock by climate-response type, 2000\u20132025", loc="left")
ax.legend(frameon=False, fontsize=9, loc="upper left")
ax.set_xlim(2000, 2025)
fig.tight_layout()
fig.savefig(f"{OUT}/fig2_response_type.pdf", bbox_inches="tight")
fig.savefig(f"{OUT}/fig2_response_type.png", dpi=300, bbox_inches="tight")
plt.close(fig)

# ---------------------------------------------------------------
# Figure 3: Development gradient -- HDI tier
# Panel A: % of total legislation that is health-relevant
# Panel B: institutional integration rate (% of health-relevant)
# ---------------------------------------------------------------
order = ["Very High", "High", "Medium", "Low"]
agg = hdi.groupby("HDI")[["Total documents", "Health-relevant documents", "Institutional health roles"]].sum()
agg = agg.loc[order]
agg["pct_health_relevant"] = 100 * agg["Health-relevant documents"] / agg["Total documents"]
agg["pct_institutional"] = 100 * agg["Institutional health roles"] / agg["Health-relevant documents"]

fig, axes = plt.subplots(1, 2, figsize=(9.5, 4.0))
seq_colors = ["#08306b", "#3182bd", "#9ecae1", "#deebf7"]  # dark->light, Very High->Low

ax = axes[0]
bars = ax.bar(order, agg["pct_health_relevant"], color=seq_colors, edgecolor="white")
ax.set_ylabel("Health-relevant legislation\n(% of all climate legislation)")
ax.set_title("A   Development gradient: legislative breadth", loc="left")
ax.set_ylim(0, 75)
for b, v in zip(bars, agg["pct_health_relevant"]):
    ax.text(b.get_x()+b.get_width()/2, v+1.5, f"{v:.1f}%", ha="center", fontsize=9)

ax = axes[1]
bars = ax.bar(order, agg["pct_institutional"], color=seq_colors, edgecolor="white")
ax.set_ylabel("Institutional integration rate\n(% of health-relevant documents)")
ax.set_title("B   Institutional integration: not monotonic", loc="left")
ax.set_ylim(0, 17)
for b, v in zip(bars, agg["pct_institutional"]):
    lab = f"{v:.1f}%" if v > 0 else "0% (0/267)"
    ax.text(b.get_x()+b.get_width()/2, v+0.3, lab, ha="center", fontsize=9)

for a in axes:
    a.set_xlabel("Human Development Index tier")

fig.tight_layout()
fig.savefig(f"{OUT}/fig3_hdi_gradient.pdf", bbox_inches="tight")
fig.savefig(f"{OUT}/fig3_hdi_gradient.png", dpi=300, bbox_inches="tight")
plt.close(fig)

# ---------------------------------------------------------------
# Figure 4: Regional patterns -- institutional integration rate
# Panel A: Lancet Countdown region, Panel B: WHO region
# ---------------------------------------------------------------
def region_table(df, col):
    a = df.groupby(col)[["Health-relevant documents", "Institutional health roles"]].sum()
    a["pct"] = 100 * a["Institutional health roles"] / a["Health-relevant documents"]
    return a.sort_values("pct", ascending=True)

lc_t = region_table(lc, "LC")
who_t = region_table(who, "WHO")

fig, axes = plt.subplots(1, 2, figsize=(10.5, 4.6))

ax = axes[0]
colors = [C_VERMIL if v < 2 else (C_ORANGE if v < 10 else C_TEAL) for v in lc_t["pct"]]
ax.barh(lc_t.index, lc_t["pct"], color=colors, edgecolor="white")
for i, v in enumerate(lc_t["pct"]):
    ax.text(v+0.3, i, f"{v:.1f}%", va="center", fontsize=8.5)
ax.set_xlabel("Institutional integration rate\n(% of health-relevant documents)")
ax.set_title("A   Lancet Countdown region", loc="left")
ax.set_xlim(0, 24)

ax = axes[1]
colors = [C_VERMIL if v < 2 else (C_ORANGE if v < 10 else C_TEAL) for v in who_t["pct"]]
ax.barh(who_t.index, who_t["pct"], color=colors, edgecolor="white")
for i, v in enumerate(who_t["pct"]):
    ax.text(v+0.3, i, f"{v:.1f}%", va="center", fontsize=8.5)
ax.set_xlabel("Institutional integration rate\n(% of health-relevant documents)")
ax.set_title("B   WHO region", loc="left")
ax.set_xlim(0, 20)

fig.tight_layout()
fig.savefig(f"{OUT}/fig4_regional.pdf", bbox_inches="tight")
fig.savefig(f"{OUT}/fig4_regional.png", dpi=300, bbox_inches="tight")
plt.close(fig)

print("All figures written to", OUT)
import os
for f in sorted(os.listdir(OUT)):
    print(" -", f)